### PR TITLE
Fix #2954

### LINKED ISSUE #2954: Layout Options context menu over maximize button is not visible on Win11
Happens only when "Style the windows title bar" is active in Options => Display.

### PR DESCRIPTION
**Pull request by tom-englert**
Link to issue(s) this covers
#2954

### Problem
Layout Options context menu over maximize button is not visible on Win11

### Solution
Update dependencies, see https://github.com/tom-englert/TomsToolbox/issues/16

### CODE REVIEW

**Comment by christophwille** [comment]
before

image

after

image

Where did the rounded corners go, why is there now a window border?

**Comment by tom-englert** [comment]
That's the custom style, there were never rounded corners.

**Comment by christophwille** [comment]
7320 is the latest main build - why on earth does that have rounded corners then?

image

**Comment by tom-englert** [comment]
Wow - that puzzles me. How does 7320 look with a dark theme?

**Comment by christophwille** [comment]
image

Binary in question: https://github.com/icsharpcode/ILSpy/suites/12092398590/artifacts/636778355

My Win11 settings re:theme

image

**Comment by tom-englert** [comment]
Looks we can have either rounded corners or the "Layout Options". Unfortunately I don't have any physical Win11 machine to investigate further.

**Comment by christophwille** [comment]
Chrome theming seems to be a minefield as usual... dang. So far, every options seems to have serious downsides. Either "looks like every other window" or "works like every other window". Myself, I lean a bit more towards the "looks like every other window" because that is what most people are going to see.

**Comment by tom-englert** [comment]
I think this is the main reason for having this optional and off by default

**Comment by tom-englert** [comment]
Btw. How does Visual Studio look on Win11?

**Comment by christophwille** [comment]
VS (usually have it fullscreen):

image

**Comment by tom-englert** [comment]
@christophwille can you please try again with this version?

**Comment by christophwille** [comment]
On Windows 11, this now looks "like every other app" and works as expected. Did you test on Windows 10 too? (I don't have that around) @siegfriedpammer could you give this a go please?

**Comment by christophwille** [comment]
btw, @tom-englert given that we now have so many issues & prs open in this area - what is your take on what we should go with (and what to close)? To me it seems this PR does what people would expect, do we need any of the other Win32 API calls?

**Comment by greenozon** [comment]
Anyone testing these modern changes on Win7, Win8?
these are still pretty much in use...

**Comment by christophwille** [comment]
> Anyone testing these modern changes on Win7, Win8? these are still pretty much in use...

Out-of-support operating system are not being tested on. If it works, great.

**Comment by tom-englert** [comment]
< Did you test on Windows 10 too?

Yes, that's my dev env

**Comment by christophwille** [comment]
Thanks!

**Comment by tom-englert** [comment]
> btw, @tom-englert given that we now have so many issues & prs open in this area - what is your take on what we should go with (and what to close)? To me it seems this PR does what people would expect, do we need any of the other Win32 API calls?

- I think #2951 can be closed, that's working fine now with this PR
- #2948 / #2950 would still give some benefits to Win11 users, since it delegates styling of the title bar to Windows itself, so it will work out of the box without configuration, and also respect accent color settings correctly (show accent color on title bar enabled)

**Pull request merged**
