### PR TITLE
Improving csproj Export (Save Code)

### PR DESCRIPTION
**Pull request by wwh1004**
Link to issue: https://github.com/icsharpcode/ILSpy/issues/2121

### CODE REVIEW

**Comment by wwh1004** [comment]
if i have time and i can do it, i will add other patches

**Comment by siegfriedpammer** [comment]
Is this still in progress? If yes, please convert it to a draft. Thanks!

**Comment by wwh1004** [comment]
@siegfriedpammer now i finish all parts of https://github.com/icsharpcode/ILSpy/issues/2121

**Comment by siegfriedpammer** [comment]
Thank you for your contribution. This is a bigger change and currently I don't have enough time to sit down and review this, I am sorry, I will try to get to it as soon as possible, however it might take one or two weeks.

**Comment by wwh1004** [comment]
No problem

**Comment by siegfriedpammer** [comment]
Thank you for your contribution!
Sorry for taking so long to review this...
I am very very sorry for force-pushing the wrong branch to your fork.

**Pull request closed without merging**
