### PR TITLE
Support multiple Tabs in ILSpy

### PR DESCRIPTION
**Pull request by Radon222**
I've added support for multiple tabs in ILSpy, each tab would contain a DecompilerTextView, so you can open several tabs in one instance without opening several ILSpy instances. 

This would resolve issue #119 

Added a toolbar button to created a new tab, see below:

image

Also added a menu entry under File menu, see below

image

Feel free to make comments :+1:

### CODE REVIEW

**Comment by Radon222** [comment]
@siegfriedpammer @arturek @Matthew-Bonner @Verser @migig @eusebiu

**Comment by christophwille** [comment]
We currently are (and have been for quite a while) discussing "future directions of the UI". We want to go cross platform, and we definitely want to take that opportunity to modernize the UX: current thinking is MDI, which would get us a lot of the requested functionality - like SxS-viewing of decompilation results (think comparing different versions of a codebase). Maybe @siegfriedpammer could chime in with some of the UX ideas.

**Comment by siegfriedpammer** [comment]
Our idea basically was to support multiple open documents and allow to stack them side-by-side, i.e., full-blown docking like VS. This allows comparing of versions, comparing C# and IL, looking and XAML resources while reading C# or IL, etc.

**Comment by christophwille** [comment]
To be replaced by https://github.com/icsharpcode/ILSpy/tree/avalondock

**Comment by christophwille** [comment]
#1724 contains the feature discussion

**Comment by siegfriedpammer** [comment]
Thank you for the pull request!

We have implemented an improved version of this based on AvalonDock in #1801, which was merged to master a few minutes ago.

I hope you like the new docking features and if there still is something missing, please feel free to open a pull request!

**Pull request closed without merging**
