### PR TITLE
Default app.config that allows VS to build in correct order

### LINKED ISSUE #1731: Initial Checkout Visual Studio Build Failure
When executing Build/Build in VS 16.3 (and earlier) on a fresh git clone checkout in a blank directory, build fails:

```1>------ Build started: Project: ICSharpCode.TreeView, Configuration: Debug Any CPU ------
2>------ Build started: Project: ICSharpCode.Decompiler, Configuration: Debug Any CPU ------
2>ILSpyUpdateAssemblyInfo225442377
1>ICSharpCode.TreeView -> D:\Demos\ILSpy-blankcheckout1\SharpTreeView\bin\Debug\net472\ICSharpCode.TreeView.dll
2>ICSharpCode.Decompiler -> D:\Demos\ILSpy-blankcheckout1\ICSharpCode.Decompiler\bin\Debug\netstandard2.0\ICSharpCode.Decompiler.dll
2>Successfully created package 'D:\Demos\ILSpy-blankcheckout1\ICSharpCode.Decompiler\bin\Debug\ICSharpCode.Decompiler.6.0.0.5240-alpha1-debug.nupkg'.
2>Done building project "ICSharpCode.Decompiler.csproj".
3>------ Build started: Project: ICSharpCode.Decompiler.Tests, Configuration: Debug Any CPU ------
4>------ Build started: Project: ICSharpCode.Decompiler.PdbProvider.Cecil, Configuration: Debug Any CPU ------
5>------ Build started: Project: ILSpy.BamlDecompiler, Configuration: Debug Any CPU ------
6>------ Build started: Project: TestPlugin, Configuration: Debug Any CPU ------
3>ICSharpCode.Decompiler.Tests -> D:\Demos\ILSpy-blankcheckout1\ICSharpCode.Decompiler.Tests\bin\Debug\net472\ICSharpCode.Decompiler.Tests.exe
7>------ Build started: Project: ILSpy.Tests, Configuration: Debug Any CPU ------
4>ICSharpCode.Decompiler.PdbProvider.Cecil -> D:\Demos\ILSpy-blankcheckout1\ICSharpCode.Decompiler.PdbProvider.Cecil\bin\Debug\netstandard2.0\ICSharpCode.Decompiler.PdbProvider.Cecil.dll
7>CSC : error CS0006: Metadata file 'D:\Demos\ILSpy-blankcheckout1\ILSpy\bin\Debug\net472\ILSpy.exe' could not be found
7>Done building project "ILSpy.Tests.csproj" -- FAILED.
5>CSC : error CS0006: Metadata file 'D:\Demos\ILSpy-blankcheckout1\ILSpy\bin\Debug\net472\ILSpy.exe' could not be found
5>Done building project "ILSpy.BamlDecompiler.csproj" -- FAILED.
8>------ Build started: Project: ILSpy.BamlDecompiler.Tests, Configuration: Debug Any CPU ------
9>------ Build started: Project: ILSpy.AddIn, Configuration: Debug Any CPU ------
6>CSC : error CS0006: Metadata file 'D:\Demos\ILSpy-blankcheckout1\ILSpy\bin\Debug\net472\ILSpy.exe' could not be found
6>Done building project "TestPlugin.csproj" -- FAILED.
9>CSC : error CS0006: Metadata file 'D:\Demos\ILSpy-blankcheckout1\ILSpy\bin\Debug\net472\ILSpy.exe' could not be found
9>Done building project "ILSpy.AddIn.csproj" -- FAILED.
8>CSC : error CS0006: Metadata file 'D:\Demos\ILSpy-blankcheckout1\ILSpy\bin\Debug\net472\ILSpy.BamlDecompiler.Plugin.dll' could not be found
8>CSC : error CS0006: Metadata file 'D:\Demos\ILSpy-blankcheckout1\ILSpy\bin\Debug\net472\ILSpy.exe' could not be found
8>Done building project "ILSpy.BamlDecompiler.Tests_2qz4kodo_wpftmp.csproj" -- FAILED.
========== Build: 4 succeeded, 5 failed, 1 up-to-date, 0 skipped ==========
```

Sometimes, the following error shows up in the log too:
```
Error	MSB4018	The "WriteAppConfigWithSupportedRuntime" task failed unexpectedly. System.IO.FileNotFoundException: Could not find file 'D:\Demos\ILSpy-blankcheckout1\ILSpy\app.config'.
```
An immediately following Build/Rebuild works as expected. It seems that VS doesn't respect project dependencies on the initial Build/Build. 

If I copy ILSpy\app.config from a previous checkout (where ILSpyUpdateAssemblyInfo already had run) to a new blank checkout, initial Build/Build works. It seems that the missing app.config - which is generated from a template via ILSpyUpdateAssemblyInfo task - messes up Visual Studio's build ordering because neither AppVeyor nor Azure Pipelines has this "on initial checkout" build problem.

### PR DESCRIPTION
**Pull request by christophwille**
Fixes #1731

### CODE REVIEW

**Comment by christophwille** [comment]
Verified https://ci.appveyor.com/project/icsharpcode/ilspy/builds/27823130/job/1460vi716q3irwry/artifacts - AppVeyor does create the app.config properly & packages it as before

**Comment by dgrunwald** [comment]
This file gets overwritten by the build?

But then it'll constantly count up the version number with every commit; and will be a constant source of merge conflicts when using branches.

**Comment by siegfriedpammer** [comment]
IIRC, it won't, because it is in .gitignore. Only the "initial" version is in version control.

**Comment by christophwille** [comment]
It is ignored as is today.

**Comment by siegfriedpammer** [comment]
Turns out, it is a bit more complicated than that:
https://stackoverflow.com/questions/4348590/how-can-i-make-git-ignore-future-revisions-to-a-file

**Comment by christophwille** [comment]
ok, that doesn't get us to where we want to be, closing.

**Pull request closed without merging**
