### PR TITLE
Fix insertion of result at end position

### PR DESCRIPTION
**Pull request by MikeFH**
### Problem
When using "sort result by fitness", some results are not sorted in correct order.

### Solution
* Fix insertion when result has to be inserted at the end (it was inserted at the second last position before)

### CODE REVIEW

**Comment by siegfriedpammer** [comment]
What's the reason for this change? I don't see a bug that needs fixing on that line... please explain. Thanks!

**Comment by siegfriedpammer** [comment]
Thank you for the fix... however, I wonder, wouldn't it make sense to refactor that part of the code? ... I think, it would be easy to use BinarySearch just as in the "Original Code" path. Also O(log N) vs O(N) for each result is a nice improvement.

**Comment by siegfriedpammer** [comment]
I will merge this and do the refactoring on top of that... so your contribution does not get lost. Thanks!

**Comment by MikeFH** [comment]
I didn't want to change too many things, but I don't mind refactoring the method as you suggested.

**Pull request merged**
