### PR TITLE
Do not merge yet: Fix decompiler to work with Roslyn-compiled code

### LINKED ISSUE #502: ILSpy doesn't handle non-trivial language features from Roslyn compilers
Existing features like `switch` blocks, lambdas, iterators, and especially async are compiled differently by the Roslyn compiler, and ILSpy generates very ugly code for them (sometimes failing entirely).

These issues are especially evident when trying to decompile Dev14 itself, which is all compiled with Roslyn.

I will change the decompiler test cases to run each test with both the Roslyn compiler and the legacy compiler, and fix as many of the breakages as I can.

### PR DESCRIPTION
**Pull request by SLaks**
Fixes #502 

This is an ongoing pull request; I will keep pushing commits as I fix more issues.

You can merge this whenever you want; I'll make new pull requests as I make more fixes.  (it would be better to merge more often)

The first 8 commits are from #501.
Can you please merge that before looking at this PR?
Once you do that, I'll rebase this so that it starts from upstream HEAD, without the duplicate commits.

### CODE REVIEW

**Comment by siegfriedpammer** [comment]
Any update on this?

**Comment by SLaks** [comment]
No; I haven't had time to work on this for a while.
There is also the question of #519.

**Comment by SamB** [comment]
Hmm, well, it doesn't seem like you should avoid fixing bugs *just* because it isn't clear how best to test for their recurrence.

**Comment by SLaks** [comment]
Sorry; I do not have time to work on this at the moment.

**Pull request closed without merging**
