### PR TITLE
Add Chinese translation

### PR DESCRIPTION
**Pull request by Berrysoft**
Well, I found that someone has done that in #2066 , after I completed these works... but I believe my translation is better.🤣

Therefore I still choose to open this pull request, and @maikebing maybe we should have a compromise about these translations. You did great work in the past, but I believe some of your translations was done by a translation software, because they are not that native. I fixed them in this pull request.

- [x] Add new translations
- [x] Fix symbols and punctuations
- [x] Fix spaces
- [x] Remove useless translations

### CODE REVIEW

**Comment by maikebing** [comment]
@Berrysoft 
Hello, compare #2066 looks like there's some repetitive work,  I don't like to judge who's better, But I want to further optimize it based on https://github.com/icsharpcode/ILSpy/pull/2066 .Some content may be proposed for discussion with @yyjdelete and me!

**Comment by Berrysoft** [comment]
@maikebing I'd like to discuss about them. How? Maybe I should open a pull request to your branch?

**Comment by maikebing** [comment]
Well, I think it's better.

**Comment by maikebing** [comment]
Finish it together.

**Comment by Berrysoft** [comment]
OK, I'll open one to your branch later.

**Comment by Berrysoft** [comment]
@maikebing I opened a [pull request](https://github.com/maikebing/ILSpy/pull/1) to your branch.

**Pull request closed without merging**
