### PR TITLE
Fix 1362 Removed string literals in favor of nameof usage

### PR DESCRIPTION
**Pull request by siriak**
Fixes issue #1362 Removed string literals and utilized nameof()

### CODE REVIEW

**Comment by siegfriedpammer** [comment]
Thank you for the contribution!

```
Results (nunit3) saved as TestResult.xml
python BuildTools\tidy.py
.\ILSpy\FilterSettings.cs:117: Line starting with spaces. Use tabs for indentation instead!
.\ILSpy\FilterSettings.cs:118: Line starting with spaces. Use tabs for indentation instead!
.\ILSpy\FilterSettings.cs:119: Line starting with spaces. Use tabs for indentation instead!
.\ILSpy\FilterSettings.cs:120: Line starting with spaces. Use tabs for indentation instead!
Tidy check: failed
Command exited with code 1
```

We require all indentation to be done with tabs.

**Comment by sungam3r** [comment]
A little more:
https://github.com/icsharpcode/ILSpy/blob/master/ILSpy/AboutPage.cs#L239
https://github.com/icsharpcode/ILSpy/blob/master/ILSpy/AboutPage.cs#L252
https://github.com/icsharpcode/ILSpy/blob/master/ILSpy/LoadedNugetPackage.cs#L63

**Comment by siegfriedpammer** [comment]
Thank you for helping out with this, but please note that the code base of ILSpy (the WPF part, not the decompiler engine) uses an older style - pre C# 5 in most parts. It is not even updated to use async-await or MVVM.

I am not sure if one single pull request will be enough to update it all.

**Comment by sungam3r** [comment]
Ok.

**Comment by siriak** [comment]
Updated pull request

**Comment by siegfriedpammer** [comment]
Is this finished and can be merged?

**Comment by sungam3r** [comment]
LGTM

**Comment by siegfriedpammer** [comment]
Thank you very much!

**Pull request merged**
