### PR TITLE
Resource search strategy

### PR DESCRIPTION
**Pull request by miloush**
Adds searching resources including .resource files and tree navigation. Because of recent changes to cache entity result icons, I combined the approaches of myself and @sailro, splitting both results and strategies.

image

### CODE REVIEW

**Comment by siegfriedpammer** [comment]
Wonderful! Thank you so much! Can you please do XAML search next? ;-)

**Comment by miloush** [comment]
Thanks. As in decompiling BAML and doing text search on it?

**Comment by siegfriedpammer** [comment]
Yes, decompiling BAML. This might be very slow... I think we'll have to figure out how to handle it efficiently. Checking for x:Key/x:Name/Name/x:Uid/TargetType attributes should be enough...

Do you think we could use the BAML decompiler for this purpose?

**Comment by siegfriedpammer** [comment]
I think first we will have to define an extension point for search strategies... then the BamlDecompiler AddIn can add an implementation for BAML.

**Comment by siegfriedpammer** [comment]
We could continue this discussion in #846.

**Pull request merged**
