### PR TITLE
modify the using pattern to also detect F# [#670]

### PR DESCRIPTION
**Pull request by 0x53A**
https://gist.github.com/0x53A/5c8dedc0be448a299386#file-c-with-my-changes

### CODE REVIEW

**Comment by dgrunwald** [comment]
What if the `disposable` variable is still used later (after the finally-block)?
You're changing semantics by effectively removing the variable assignment.

`TransformUsings` already checks that `ident` is not used after the try-catch statement (the `IsVariableValueUnused` call); you'll need to add the same check for the `disposable` variable.

**Comment by 0x53A** [comment]
Thanks, I did not think about that case.

I will fix it (and maybe add a unit test) next week.

**Comment by 0x53A** [comment]
Ok, looks good from my side. @dgrunwald , could you please take a look?

**Comment by dgrunwald** [comment]
When running the tests locally on my machine, the F# tests fail with two F# compiler errors:
<startup (1,1)-(1,81) parameter error Could not resolve this reference. Could not locate the assembly "FSharp.Core, Version=4.4.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a". Check to make sure the assembly exists on disk. If this reference is required by your code, you may get compilation errors. (Code=MSB3245)>,
<startup (1,1)-(1,81) parse error internal error: BuildFrameworkTcImports: no resolution of 'FSharp.Core, Version=4.4.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'>

Instead of running various compilers as part of our tests, perhaps we should commit disassembled binaries as `.il` files and re-assemble them in the tests?

**Comment by 0x53A** [comment]
The Test now uses ILASM to compile checked-in IL instead of running the F# compiler.
I have also removed references to FSharp.Core from the IL.

**Pull request merged**
