### PR TITLE
Fix possible ObservableCollection re-entrance crash when trying to na…

### PR DESCRIPTION
**Pull request by tom-englert**
…vigate to a collapsed item.

### CODE REVIEW

**Comment by siegfriedpammer** [comment]
Thank you very much!

**Comment by siegfriedpammer** [comment]
Looking at ILSpy/AssemblyTree/AssemblyTreeModel.cs as a whole I see that we sometimes do a null check (or ?) on `activeView` and sometimes don't. Is this intentional?

**Comment by tom-englert** [comment]
I think that should be always, I'm just not used to work without NRTs enabled 😔

**Comment by tom-englert** [comment]
I'll fix this

**Comment by siegfriedpammer** [comment]
you can enable NRT on any file you touch, if you think it makes work easier... however, please not all files at once... that will be a pain to review and there already is some work done in #3295

**Pull request merged**
