### PR TITLE
[FIX] Shallow clone is not supported

### PR DESCRIPTION
**Pull request by shurivich**
This PR fixes issue https://github.com/icsharpcode/ILSpy/issues/2572

### CODE REVIEW

**Comment by christophwille** [comment]
Does that fix or mask the problem?

**Comment by siegfriedpammer** [comment]
We won't be able to calculate the correct revision from a shallow clone, as it only contains the most recent revision.

```
ILSpy-shallow>git rev-list --count d779383cb85003d6dabeb976f0845631e07bf463..HEAD
fatal: Invalid revision range d779383cb85003d6dabeb976f0845631e07bf463..HEAD
```

A possible fix is to ignore the output, if it's not numeric, as this PR proposes. I would say this is an acceptable solution.

**Comment by siegfriedpammer** [comment]
One more thing, I would prefer the function to return 0 in this case... just like in the No-Git case...

**Comment by shurivich** [comment]
> One more thing, I would prefer the function to return 0 in this case... just like in the No-Git case...

It's may be not clear from code, but this is exactly what happening:
`((git rev-list --count "$baseCommit..HEAD") -as [Int32]) + $baseCommitRev`
Is recalculated to be zero.

As more robust solution, I can suggest surrounding `gitVersion` (and probably `gitCommitHash)`?) with `try..catch`, that will return 0 in case of exception.

**Comment by siegfriedpammer** [comment]
I have fixed this by adding try-catch handling to the respective parts of the powershell script. Thanks for reporting!

**Pull request closed without merging**
