### PR TITLE
Fix url of SearchMsdn when do search with generic types and .ctor methods

### PR DESCRIPTION
**Pull request by yyjdelete**
Before: https://docs.microsoft.com/dotnet/api/system.collections.generic.dictionary.keycollection..ctor
After: https://docs.microsoft.com/dotnet/api/system.collections.generic.dictionary-2.keycollection.-ctor

### CODE REVIEW

**Comment by siegfriedpammer** [comment]
Maybe this will need adjustments for static constructors (.cctor) and operators (op_) as well?

**Comment by yyjdelete** [comment]
operators already works
https://docs.microsoft.com/dotnet/api/system.decimal.op_explicit

`.cctor` should always be private and already be disabled by checks in `bool IsEnabled(TextViewContext context)`.

----

But I'm not sure which is better for enum and delegate, add special logic for them to use DeclaringType instead, or simply disable it in IsEnabled, or just leave it as it is before.
There is only
https://docs.microsoft.com/en-us/dotnet/api/system.dayofweek
but not
https://docs.microsoft.com/en-us/dotnet/api/system.dayofweek.sunday
https://docs.microsoft.com/en-us/dotnet/api/system.dayofweek.value__

**Comment by siegfriedpammer** [comment]
Enum values and delegate members should just return false for IsEnabled, I think.

**Comment by siegfriedpammer** [comment]
Thank you for your contribution!

**Pull request merged**
