### PR TITLE
Fix await calls not getting decompiled correctly

### PR DESCRIPTION
**Pull request by mohe2015**
Original:
```
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace ILSpyBugs
{
	class Class1
	{
		private static async Task<T> RequestResultAsync<T>()
		{
			return await Task.Run(async delegate {
				return default(T);
			});
		}
	}
}
```
Was decompiled to:
```
// ILSpyBugs.Class1
using System;
using System.Runtime.CompilerServices;
using System.Threading.Tasks;

internal class Class1
{
	private static async Task<T> RequestResultAsync<T>()
	{
		TaskAwaiter<T> taskAwaiter = Task.Run<T>((Func<Task<T>>)(() => default(T))).GetAwaiter();
		if (!taskAwaiter.IsCompleted)
		{
			await taskAwaiter;
			TaskAwaiter<T> taskAwaiter2 = default(TaskAwaiter<T>);
			taskAwaiter = taskAwaiter2;
			int num;
			int num2 = num = -1;
		}
		return taskAwaiter.GetResult();
	}
}
```
Now gets decompiled to:
```
// ILSpyBugs.Class1
using System;
using System.Threading.Tasks;

internal class Class1
{
	private static async Task<T> RequestResultAsync<T>()
	{
		return await Task.Run<T>((Func<Task<T>>)(() => default(T)));
	}
}
```

### CODE REVIEW

**Comment by mohe2015** [comment]
Please review.

**Comment by dgrunwald** [comment]
Thanks, the changes look good to me.

Just a small improvement: you can match the pattern `stobj(ldflda field(target), value)` in a single call: `block.Instructions[pos + 1].MatchStFld(out target, out field, out value)`.
(Whenever you see `stfld field(target, value)` in the ILAst or a comment, that's just syntax sugar; the ILAst always uses stobj/ldobj+ldflda to represent field loads/stores, there's no `OpCode.StFld`)

**Comment by mohe2015** [comment]
@dgrunwald Done! Thank you for the explanation.

**Comment by chucklu** [comment]
@mohe2015  similar  problem [here](https://github.com/icsharpcode/ILSpy/issues/1632)

**Pull request merged**
