### PR TITLE
Add assembly search strategy

### PR DESCRIPTION
**Pull request by miloush**
Searching assemblies by full name. Shows file path in Location column.

image

### CODE REVIEW

**Comment by siegfriedpammer** [comment]
Would it be useful to add the file name as an additional criterion? That is `asm.FullName.Contains OR asm.FileName.Contains`. Of course each assembly would only be displayed once in the result list.

**Comment by miloush** [comment]
I flavoured the assembly search, you can now match name (`a:`), full name (`afn:`), file name (`af:`), culture (`ac:`), version (`av:`), and others (`apk:`, `aha:`, `afl:`). Does that address your concern, or were you looking for an actual OR? We could make `a:` to be assembly name or file name and `an:` name only.

Speaking of which, the tree view seems to show file names without extension rather than assembly names. In most cases they are the same but I got a few assemblies where the file name does not match the assembly name, the result being that the "Name" column in search results does not show the same label as the tree view for the same assembly. Was that a deliberate choice, or is that something worth aligning?

**Comment by siegfriedpammer** [comment]
> I flavoured the assembly search, you can now match name (`a:`), full name (`afn:`), file name (`af:`), culture (`ac:`), version (`av:`), and others (`apk:`, `aha:`, `afl:`). Does that address your concern, or were you looking for an actual OR? We could make `a:` to be assembly name or file name and `an:` name only.

Wow... that are a lot of options... I thought that maybe `a:` should be equal to `assemblies.Where(a => a.FullName.Contains("<search-term>") || a.FileName.Contains("<search-term>")`. All the options might be overkill.

> Speaking of which, the tree view seems to show file names without extension rather than assembly names. In most cases they are the same but I got a few assemblies where the file name does not match the assembly name, the result being that the "Name" column in search results does not show the same label as the tree view for the same assembly. Was that a deliberate choice, or is that something worth aligning?

Yes, I think we should use the assembly name in both cases... The filename will be displayed in the tooltip anyway.

cc @christophwille @dgrunwald what do you think?

**Comment by christophwille** [comment]
I am content with simply using "a:" to mean "wildcard-search in full asm name". I should be rather unusual that version string collides with culture or file name.

**Comment by dgrunwald** [comment]
> Yes, I think we should use the assembly name in both cases... The filename will be displayed in the tooltip anyway.

For our own usage I'd prefer the file name, so that we can easily distinguish the variants of our test cases (`AssemblyName.dll`, `AssemblyName.opt.dll`, etc.).

**Comment by siegfriedpammer** [comment]
> > Yes, I think we should use the assembly name in both cases... The filename will be displayed in the tooltip anyway.
> 
> For our own usage I'd prefer the file name, so that we can easily distinguish the variants of our test cases (`AssemblyName.dll`, `AssemblyName.opt.dll`, etc.).

Yes, you are right. I'd forgot about that...

**Comment by miloush** [comment]
Okay so we are concluding that we want two options, full assembly name and file path?

**Comment by siegfriedpammer** [comment]
> Okay so we are concluding that we want two options, full assembly name and file path?

Are you talking about two different search "prefixes"/options or display options in the tree view?

From what I gather from the other responses, the best route to take would be:

* keep the tree view as is,
* use only one search "prefix"/option: `a:` to search the full assembly name OR file name, as in: `assemblies.Where(a => a.FullName.Contains(searchTerm) || a.FileName.Contains(searchTerm))`,
* the other separate options for version, culture and pk-token are overkill.

Do you agree?

**Comment by miloush** [comment]
Tree view is a separate issue.
I agree all the options are overkill, as they can be matched using regex on the full name.

I am a bit worried about the full path to be included by default. Many assemblies are typically under the same directory and we might get lots of false positives when searching e.g. for Microsoft.

I suggest a compromise:
`a:` matching assembly local name OR file name without path
`an:` matching assembly full name
`af:` matching assembly full path

**Comment by siegfriedpammer** [comment]
Yes, I think this is a good compromise...

@dgrunwald are you OK with these changes?

**Comment by siegfriedpammer** [comment]
@miloush Thank you for contributing this feature!

**Pull request merged**
