### PR TITLE
Implement mass decompilation in ICSharpCode.Decompiler.Console

### PR DESCRIPTION
**Pull request by mohe2015**
No whitespace changes: https://github.com/icsharpcode/ILSpy/pull/879/files?w=1

### CODE REVIEW

**Comment by siegfriedpammer** [comment]
Thank you for your continued interest in contributing. One note: Can you please pay more attention to keeping the whitespace intact? We'd prefer reading diffs without the ?w=1 option. Please check your files before committing and revert any whitespace-only changes.

**Comment by siegfriedpammer** [comment]
One useful thing would be using the pre-commit hook as described in the README.md.

**Comment by mohe2015** [comment]
I thought I added it last time. Maybe Visual Studio's git integration does not work well.  I will fix that tomorrow.

**Comment by dgrunwald** [comment]
I think in this case it's the original indentation that was wrong.
The tidy.py script isn't checking the ICSharpCode.Decompiler.Console directory, and the console app was originally created in a different repo without our .editorconfig in place.

**Comment by mohe2015** [comment]
Merge or change something?

**Comment by dgrunwald** [comment]
I'm not so sure we actually want this as a feature. It very much seems like it's something that could be left to `find | xargs` (though the separate output directories might be tricky in a shell script).

**Comment by mohe2015** [comment]
@dgrunwald For Windows it could be convenient, couldn't it?

**Comment by mohe2015** [comment]
Found a way how to do it on windows. Execute the following script in the git shell using `bash script.sh`:
```
cd "binariesdir"
find . -type f \( -name "*.exe" -or -name "*.dll" \) -print0 | while IFS= read -r -d $'\0' line; do
    echo "$line"
    target="outputdir/${line::-4}"
    mkdir -p "$target"
    dotnet "ilspydir/ICSharpCode.Decompiler.Console/bin/Release/netcoreapp2.0/ilspycmd.dll" "$line" -p -o "$target"
done
```

**Pull request closed without merging**
