### PR TITLE
ILSpy  Internationalization

### PR DESCRIPTION
**Pull request by maikebing**
The Chinese translation has been completed！

### CODE REVIEW

**Comment by maikebing** [comment]
@siegfriedpammer
 The Chinese translation has been completed

**Comment by siegfriedpammer** [comment]
@maikebing Thank you for doing all the internationalization work on ILSpy.

I made just a few changes:
* I moved all the resources from the ICSharpCode.Decompiler assembly to ILSpy.exe because we do not want to ship resources with the decompiler engine.
* I removed the translation of the exception text for local functions as those do not need translation because the exception should not be visible to ILSpy users.

@dgrunwald Do you think we can get this merged soon? Please have a look as well, thank you!

**Comment by maikebing** [comment]
Hey，You can merge it. 
Thank you for making ILSpy so great.

**Comment by siegfriedpammer** [comment]
Thank you for providing this pull request!

**Pull request merged**
