### PR TITLE
Test /bl for Azure Pipelines build

### PR DESCRIPTION
**Pull request by christophwille**
See #1732 

Infos http://msbuildlog.com/

### CODE REVIEW

**Comment by christophwille** [comment]
Attached is the build log (zipped binlog) for the failed Release CI (original build at https://icsharpcode.visualstudio.com/icsharpcode-pipelines/_build/results?buildId=365)

[msbuild_CI_Release.zip](https://github.com/icsharpcode/ILSpy/files/3708460/msbuild_CI_Release.zip)

**Comment by onovotny** [comment]
This is weird. I'd suggest @nguerrera or @dsplaisted might be able to help?

**Comment by dsplaisted** [comment]
@rainersigwald Any ideas on what's going on here?

> ALINK error AL1019: Metadata failure while creating assembly -- The process cannot access the file because it is being used by another process. [d:\a\1\s\ILSpy\ILSpy.csproj]

This might be relevant:

```xml
    <EmbeddedResource Include="Properties\Resources.resx">
      <Generator>PublicResXFileCodeGenerator</Generator>
      <LastGenOutput>Resources.Designer.cs</LastGenOutput>
    </EmbeddedResource>
    <EmbeddedResource Include="Properties\Resources.zh-Hans.resx" />
```

**Comment by onovotny** [comment]
@dsplaisted what's weird is that it works in three of the four configurations?

**Comment by rainersigwald** [comment]
From the log, `ILSpy.csproj` is being built twice in parallel:
1. `ILSpy.WithPackage.sln` -> `ILSpy.csproj` (default targets)
1. `ILSpy.WithPackage.sln` -> `ILSpy.Package.wapproj` -> `ILSpy.csproj` (`Build` target, additional properties `_WapBuildingInsideVisualStudio = ; GenerateAppxPackageOnBuild = false; BuildingInsideVisualStudio = false`)

When both of those try to read/write the same file, one fails, producing this error.

I'm not sure whether this is a bug in ILSpy's build or in `Microsoft.DesktopBridge.targets`, but I strongly suspect the latter.

You can work around this by building single-threaded (not using `msbuild -m`/the `maximumCpuCount` argument to the MSBuild AzDO task), by not building the `ILSpy.WithPackage` solution, or by building `ILSpy.Package.wapproj` _instead of_ the solution. It looks like your current AppVeyor configuration might do both of the first two. I would recommend the latter, but I'm not sure how that would affect running tests in this repo.

**Comment by christophwille** [comment]
Another interesting tidbit is that the 5.0x branch never had build failures (see checkmarks on commits https://github.com/icsharpcode/ILSpy/commits/5.0.x except for real build breaks), the only difference is that 5.0x builds for net462 while master is net472.

**Comment by christophwille** [comment]
@rainersigwald removing maximumCpuCount seems to have done the trick (was the least invasive change to the build process). Still, strange why one branch is fine, while the other fails regularly.

**Comment by dgrunwald** [comment]
In addition to the net462 -> net472 change, master also upgraded MSBuild.Sdk.Extras from 2.0.24 to 2.0.54 and has the 5388a18c4622 change.

**Comment by christophwille** [comment]
I have applied the `maximumCpuCount` fix to master (got complaints already that the green checkmarks on commits aren't there although we build successfully on AppVeyor). 

Still, I want to get to the bottom of this - why did it start failing.

**Comment by christophwille** [comment]
We are sticking with the `maximumCpuCount` workaround and won't try to find/fix the underlying issue on Azure DevOps / Visual Studio / msbuild.

**Pull request closed without merging**
