### PR TITLE
Dark theme #665

### PR DESCRIPTION
**Pull request by tom-englert**
Link to issue(s) this covers

### Problem
Dark theme #665

### Solution
* just using the themable styles from https://www.nuget.org/packages/TomsToolbox.Wpf.Styles/
* fixed some style references and replaced hardcoded colors
* added syntax highlighting schemes for dark mode

### CODE REVIEW

**Comment by Dirkster99** [comment]
Pretty cool work :-) but why don't you use the same AvalonDock Style Theme (eg VS 2013) for Dark and Light? This way you would end up using a consistent look and feel for document and tool windows and docking buttons - look at the image below to see the inconsistencies:

Untitled4

Untitled3

**Comment by christophwille** [comment]
@tom-englert Once you are done, how about the following: we tweet with request for comment on this PR for early testing / feedback from devs that did dark theme in their apps with artifacts from https://github.com/icsharpcode/ILSpy/actions/workflows/build-ilspy.yml?query=workflow%3A%22Build+ILSpy%22+branch%3ADarkTheme%23665+is%3Asuccess

**Comment by siegfriedpammer** [comment]
Note: The AvalonEdit fold margin will need some adjustments as well...

Also: inline buttons need extra styling...
image

**Comment by siegfriedpammer** [comment]
Nit: the light theme should retain the typical ILSpy look (light yellowish background of the decompiler view).

**Comment by tom-englert** [comment]
@Dirkster99 missed that, thanks for mentioning...

**Comment by tom-englert** [comment]
> Note: The AvalonEdit fold margin will need some adjustments as well...

Where exactly?

**Comment by siegfriedpammer** [comment]
I just tried adding the following lines to DecompilerTextView::.ctor

			textEditor.SetValue(FoldingMargin.SelectedFoldingMarkerBackgroundBrushProperty, Brushes.LightGreen);
			textEditor.SetValue(FoldingMargin.FoldingMarkerBackgroundBrushProperty, Brushes.Green);

and it seems to work... not sure how you are able to use this with theming...

**Comment by tom-englert** [comment]
Generally not a problem, but these properties are implemented wrong in the `FoldingMargin` class, so they are not usable in XAML.

**Comment by siegfriedpammer** [comment]
As AvalonEdit is maintained by @dgrunwald and me (just as ILSpy), it would suffice if you open an issue describing the problem and the fix. I will then apply your suggested fix, so you don't have to provide two PRs... thanks!

**Comment by Dirkster99** [comment]
@siegfriedpammer Maybe its time for an update/extension in AvalonEdit where you support {themable highlightings](https://github.com/Dirkster99/AvalonEditHighlightingThemes) out of the box :-) Looking at @tom-englert stuff I am sure he can take the idea and push it even further (maybe for a later release). It would make your ILSpy live easier and I am sure there are a few people (including myself) waiting around on this one to be integrated in AvalonEdit :-)

**Comment by siegfriedpammer** [comment]
@christophwille @dgrunwald what do you think?

**Comment by christophwille** [comment]
For AvalonEdit, our mantra is low-risk changes because ILSpy as the only inhouse consumer of AvalonEdit doesn't test all areas like SharpDevelop did back in the day. Also, it is a question of "bang for the buck" vs time spent: how big a customer base is this going to be helping? (and maybe we should be moving that part of the discussion over to a new issue in AE repo)

**Comment by christophwille** [comment]
I take that @tom-englert needs to adapt the fold margins to the fixed attached properties in AvalonEdit 6.1.1?

**Comment by tom-englert** [comment]
Actually they are working fine, so it can be tested.
I can clean up the code to use proper Xaml notation probably next weekend.

**Comment by xoofx** [comment]
If you could make it also optionally OS settings dependent - that would be amazing

**Comment by siegfriedpammer** [comment]
Thank you, that's a good idea. However, ILSpy 7.0 is really close to being released and dark mode is considered an experimental feature, which still needs a lot of testing. For this reason, we will not add an automatic switch to dark mode for 7.0. For 7.1, we will consider adding it. Thank you for your understanding!

**Comment by christophwille** [comment]
@tom-englert What is the status in terms of things to do? Asking to get an idea about when the merge might happen.

**Comment by tom-englert** [comment]
From MPOV it's done

**Comment by tom-englert** [comment]
@siegfriedpammer p.s. the update of Avalon Edit worked fine

**Comment by siegfriedpammer** [comment]
More feedback...

image

Highlighting of local variable references and search results needs adjustment in dark mode.

image

Also the "wait bar" shown when decompiling is not adjusted for dark mode yet.

The SearchBar of AvalonEdit might need adjustments as well...

Not sure which of these are really high-priority, as I am not a dark mode user myself...

**Comment by siegfriedpammer** [comment]
image

Hyperlinks might need a different color to make them look good.

**Comment by tom-englert** [comment]
> Hyperlinks might need a different color to make them look good.

@siegfriedpammer any hint which highlighting scheme is used for the about view?

**Comment by siegfriedpammer** [comment]
Thanks you very much for adding this!

**Comment by siegfriedpammer** [comment]
@tom-englert well, I found something else, which should be fixed before the release:

image

image

Do you know why https://github.com/icsharpcode/ILSpy/blob/60035befbfc3b08081f86ea0ef339400450cf631/ILSpy/Metadata/Helpers.cs#L57 is working no longer?

Also changing the borders around the column headers to be less visible, would be nice... If you have an idea on how to fix this, let me know. Thanks!

**Comment by christophwille** [comment]
How about we open an issue for "Dark Theme Improvements / Bugs" so Tom has only one (current) item to monitor? We could even pin it for others to know that this is where comments / questions should go.

**Pull request merged**
