### PR TITLE
Addin: Change Package References

### PR DESCRIPTION
**Pull request by christophwille**
Fixes https://github.com/icsharpcode/ILSpy/issues/1418

### CODE REVIEW

**Comment by siegfriedpammer** [comment]
Why did you remove the project references? I think these were added in an attempt to circumvent #511...

**Comment by christophwille** [comment]
I installed the locally built package - and even tried the BAML decompiler.

**Comment by siegfriedpammer** [comment]
Yes, but did you try whether the package is built correctly after changes and rebuilding?

**Comment by christophwille** [comment]
```
  <PropertyGroup>
    <ILSpyBuildPath>..\ILSpy\bin\$(Configuration)\$(TargetFramework)\</ILSpyBuildPath>
  </PropertyGroup>
```
Is the aforementioned issue really still applicable because we are copying from ILSpy bin folder??

**Pull request merged**
