### PR TITLE
Dark theme #665 fixes

### PR DESCRIPTION
**Pull request by tom-englert**
@siegfriedpammer as requested in #2334

### CODE REVIEW

**Comment by siegfriedpammer** [comment]
Wow... you are really fast! Thanks for fixing this...

I just found another problem:

image

I am unable to find the correct location to change the background color of the tab that the cursor is currently hovering over and also the text color of the explanation looks a bit strange if everything else is black.

Sorry for throwing so many things at you currently. If I were more versed in WPF theming I would fix it myself. Thank you so much!

**Comment by tom-englert** [comment]
@siegfriedpammer no problem, better you find them before they make it into the release 😏

**Comment by siegfriedpammer** [comment]
I found another issue: The access keys of the buttons in the "Manage assembly lists..." dialog are no longer working properly... Seems the `ContentPresenter` is not setting the `RecognizesAccessKey` property to `true` somewhere.

**Comment by christophwille** [comment]
> 
> 
> I found another issue: The access keys of the buttons in the "Manage assembly lists..." dialog are no longer working properly... Seems the `ContentPresenter` is not setting the `RecognizesAccessKey` property to `true` somewhere.

@tom-englert Are you going to add the fix for this to this PR?

**Comment by tom-englert** [comment]
Just pushed...

**Comment by siegfriedpammer** [comment]
Thank you for fixing these issues so quickly!

**Comment by tom-englert** [comment]
@siegfriedpammer P.S. thanks for the thorough testing, pointing me to views and features I missed to test - most of them I even didn't know they exist. 😄

**Pull request merged**
