### PR TITLE
Windows 11 Context menu

### PR DESCRIPTION
**Pull request by modz2014**
Adding the context menu for the new Windoows 11 you need to build a msix package to be able to use the context menu

### Solution
Will be adding the Shell context when the button is clicked in the C# project at a later date 

Screenshot 2023-07-25 142126

### CODE REVIEW

**Comment by christophwille** [comment]
Sorry, but what on earth are we supposed to do with that ton of C?

**Comment by modz2014** [comment]
its the context menu for ILSpy for windows 11 it is used when creating a msix package as well do i need to upload that code as well for creating the msix pasckage

**Comment by christophwille** [comment]
There is no msix package any more. And who is supposed to verify and maintain that C code?

**Comment by modz2014** [comment]
i will im still adding more detial for it as we speak you cna just create the msix for running the context menu you dont need to use the full msix with ILSpy to install it only installs the unmanaged dll to have the context menu

**Comment by christophwille** [comment]
We keep having those discussions - please open an issue what you want to add, so we can discuss whether that fits our plan for ILSpy - and whether we are willing to take it on. C for sure is not happening.

**Comment by modz2014** [comment]
ok there is no way of making the context menu for ILSPy on windows 11 using C# i just decided to use C unless you creat the IExplorerCommand in C#

**Comment by christophwille** [comment]
Now I get what you are trying to do - the `Open in ILSpy` command not being "hidden" behind `Show more options`. I did a little digging, and that is way too much effort to take on to maintain/keep up to date/distribute for such a super-small feature of ILSpy. Yes, I get where you are coming from, but the complications...

**Comment by modz2014** [comment]
sorry should have explained a little better I'm happy to maintain this part of the project

**Comment by christophwille** [comment]
But it needs to be built (today we don't build C) and means way longer build times, it needs to be distributed, you name it. And we always look at code "we will be left holding the bag" simply because the project is 12+ years old and people come and go.

**Comment by modz2014** [comment]
simply just build it our side of the project then

**Comment by christophwille** [comment]
Feel free to create a repository just for this "ILSpy Win11 Explorer Extension", we are happy to link to it.

**Comment by modz2014** [comment]
ok i guess i will then sorry to bother you

**Pull request closed without merging**
