### PR TITLE
fix-1785

### PR DESCRIPTION
**Pull request by pvasilek**
Removed deep scanning for extra references.

### CODE REVIEW

**Comment by dgrunwald** [comment]
The compiler uses the reference assemblies, but ILSpy uses actual runtime assemblies. It's not like we can use the reference assemblies -- there can be multiple different versions of reference assemblies for which the C# compiler produces the exact same output. The compiled binary only has enough info to find the referenced runtime assemblies, not to uniquely identity the referenced compile-time assemblies.

Moreover, an assembly that had an actual type definition at compile-time may only have a type forwarder at run-time. If we did not allow type forwarders to resolve to indirectly referenced assemblies, the decompiler would lack type definitions that the compiler had available!
This is what is causing the test failures for your PR.

**Comment by pvasilek** [comment]
You do not need to uniquely identify reference assemblies as runtime assemblies of the same version or higher would have at least the same API.
If you will test the proposed fix with the #1785  code you will see the Math.E resolved correctly besides only one assembly was used and which contains only type references.
If the patch breaks other tests, it maybe:
1) other tests are wrong
2) other type resolving strategy should be used to fit the requirements. I proposed an alternative in the bug discussion.

**Comment by dgrunwald** [comment]
> You do not need to uniquely identify reference assemblies as runtime assemblies of the same version or higher would have at least the same API.

You are wrong there.

A reference assembly might have a type definition where a runtime assembly only has a `[assembly: TypeForwardedTo()]` attribute. Thus the runtime assembly alone does not provide the same API as the reference assembly -- you also need to look at the assembly that is referenced by the type forwarder. This is why the recursive assembly resolution is necessary, and why your patch breaks our tests.

**Comment by siegfriedpammer** [comment]
Superseded by #1866

**Pull request closed without merging**
