### PR TITLE
Add a unit-test for CreateSequencePoints

### PR DESCRIPTION
**Pull request by KirillOsenkov**
This is just a unit-test to simplify debugging CreateSequencePoints. Not necessarily to be committed, up to you.

### CODE REVIEW

**Comment by KirillOsenkov** [comment]
One thing that's interesting about this test is that it compiles and decompiles in memory, nothing is ever written to disk. One might consider adopting this approach instead of compiling to disk.

**Comment by siegfriedpammer** [comment]
Is it necessary to add this to 3.0.x?

**Comment by KirillOsenkov** [comment]
Nope. Any branch you want. Let me know and I can rebase if needed.

**Comment by siegfriedpammer** [comment]
Then, could you please rebase this to master? Thank you very much!

**Comment by KirillOsenkov** [comment]
Rebased against latest master and squashed.

**Comment by siegfriedpammer** [comment]
The build is failing because I fixed the typo you reported in #1044.

**Comment by siegfriedpammer** [comment]
Thank you for your contribution!

**Pull request merged**
