### PR TITLE
CWE-252 The return value of function 'Reverse' is required to be utilized.

### PR DESCRIPTION
**Pull request by agametov**

### CODE REVIEW

**Comment by christophwille** [comment]
After checking with @siegfriedpammer "Please don't force arbitrary code styles on our code base. The core team makes the rules, not some random tool."

**Comment by agametov** [comment]
@christophwille 
@siegfriedpammer
Read the docs:
 [https://docs.microsoft.com/en-us/dotnet/api/system.linq.enumerable.reverse?view=netframework-4.6](https://docs.microsoft.com/en-us/dotnet/api/system.linq.enumerable.reverse?view=netframework-4.6)
[https://docs.microsoft.com/en-us/dotnet/api/system.array.reverse?view=netframework-4.6](https://docs.microsoft.com/en-us/dotnet/api/system.array.reverse?view=netframework-4.6)

**Comment by agametov** [comment]
Example [https://dotnetfiddle.net/CWipOa](https://dotnetfiddle.net/CWipOa)

**Comment by siegfriedpammer** [comment]
Oh, sorry, my bad! That's what you get from reviewing pull requests on your phone while travelling. I wonder why this was never noticed up to now...

It's not super critical, thanks for the fix though! Sorry, for dismissing this too early!

**Comment by agametov** [comment]
No problem, @siegfriedpammer  :-)
I thought this PR doesn`t need a detailed description because of one line.
Next time I will write a detailed description! :-)

**Comment by siegfriedpammer** [comment]
Thank you for the fix!

**Pull request merged**
