### PR TITLE
Fix special cases in catch with object

### PR DESCRIPTION
**Pull request by mohe2015**

### CODE REVIEW

**Comment by dgrunwald** [comment]
What are you trying to fix?
Can you add a test case?

**Comment by mohe2015** [comment]
I have a binary with the IL instructions which are mentioned in the comments instead of the normal ones. I will try to create a test case - it's private code...

**Comment by mohe2015** [comment]
Added a test case @dgrunwald .

**Comment by dgrunwald** [comment]
Thanks!

**Pull request merged**
