### PR TITLE
Fix can't package satellite DLL

### PR DESCRIPTION
**Pull request by maikebing**

### CODE REVIEW

**Comment by siegfriedpammer** [comment]
Thank you for the fix!

@maikebing Would it be possible for you to provide a screenshot of the Chinese version of ILSpy in action for us? Thank you very much!

**Comment by christophwille** [comment]
Thanks for providing the screenshots!

**Comment by maikebing** [comment]
You can create a project in https://crowdin.com/    to make it easier for others to translate other languages

**Pull request merged**
