### PR TITLE
feature: Initial implementation of 'disasm' command line tool

### PR DESCRIPTION
**Pull request by tapika**
### Problem

Initial implementation of command line tool for using ilspy. Planned to be used for calculating checksum over assembly later on ("front end" command line tool)

Relates to ticket https://github.com/icsharpcode/ILSpy/issues/2220.

### CODE REVIEW

**Comment by siegfriedpammer** [comment]
Thank you for your interest in contributing... May I ask how this is different from the "Show IL" option of `ilspycmd`?

https://github.com/icsharpcode/ILSpy/blob/ee10d2942b381a32efd527bcc723d366e397d299/ICSharpCode.Decompiler.Console/IlspyCmdProgram.cs#L171-L182

I wonder if it would be better to integrate the missing parts of this feature into `ilspycmd` instead of creating a new command-line application. What do you think?

**Comment by siegfriedpammer** [comment]
Oh sorry, I was mislead by the name `disasm`. This is not actually related to IL disassembly but uses the C# decompiler engine. Then the question is: how is this different from the `ilspycmd` application as a whole?

https://github.com/icsharpcode/ILSpy/tree/ee10d2942b381a32efd527bcc723d366e397d299/ICSharpCode.Decompiler.Console shows the list of available options. Could you tell us, what is missing there? Thank you!

**Comment by tapika** [comment]
That's a good question - I just now noticed that you have this project, but it was in separate solution - that's why I did not detect it - otherwise would probably start from it.

But now also opened Frontends.sln, which seems to be vs2017 project - it does not compiles out of box.

May I propose that we start from disasm tool, as it should be buildable and compliable - but I can change the project name and/or front end behavior as seen necessary.

**Comment by siegfriedpammer** [comment]
> But now also opened Frontends.sln, which seems to be vs2017 project - it does not compiles out of box.

Works just fine with VS 2019 16.8.6 (latest). Which errors are you seeing?

> May I propose that we start from disasm tool, as it should be buildable and compliable - but I can change the project name and/or front end behavior as seen necessary.

I don't think this is a good idea, as `ilspycmd` is already deployed as dotnet tool. Getting it to compile on your machine most likely is just a matter of installing the required work loads/frameworks using VS 2019 installer.

Could you please share, which errors you are receiving when opening Frontends.sln? Thanks!

**Comment by siegfriedpammer** [comment]
Did you try following our "How to build" guide? https://github.com/icsharpcode/ILSpy#how-to-build

If the guide does not fix your problem, tell us so we are able to improve it! Thanks!

**Comment by tapika** [comment]
I've cleaned up git, and compilation of front end solution started to work as well.
I'll try to patch ilspycmd then, let me delete this fork / pull request, and re-create my changes in another project.

**Pull request closed without merging**
